const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS';
const GET_ALL_TYPES = 'GET_ALL_TYPES';
const GET_BY_ID = 'GET_BY_ID';
const CLEAR = 'CLEAR_ID';
const SEARCH_POKEMON = 'SEARCH_POKEMON';
const FILTER_ORDER = 'FILTER_ORDER';
const PAGINATION = 'PAGINATION';
const PAGES = 'PAGES';
const NEW_POKEMON = 'NEW_POKEMON';
const CHANGE_PAGE = 'CHANGE_PAGE';

export {
    GET_ALL_POKEMONS,
    GET_ALL_TYPES,
    GET_BY_ID,
    CLEAR,
    SEARCH_POKEMON,
    FILTER_ORDER,
    PAGINATION,
    PAGES,
    NEW_POKEMON,
    CHANGE_PAGE
}


