const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS';
const GET_ALL_TYPES = 'GET_ALL_TYPES';
const GET_BY_ID = 'GET_BY_ID';
const CLEAR_SORT = 'CLEAR_SORT';
const SEARCH_POKEMON = 'SEARCH_POKEMON';
const FILTER_POKEMONS_BY_TYPE = 'FILTER_POKEMONS_BY_TYPE';
const PAGINATION = 'PAGINATION';
const PAGES = 'PAGES';
const NEW_POKEMON = 'NEW_POKEMON';
const CHANGE_PAGE = 'CHANGE_PAGE';
const SORT_POKEMONS_BY_ASC = 'ORT_POKEMONS_BY_ASC';
const SORT_POKEMONS_BY_DESC = 'SORT_POKEMONS_BY_DESC';
const SORT_POKEMONS_BY_ATTACK_ASC = 'SORT_POKEMONS_BY_ATTACK_ASC';
const SORT_POKEMONS_BY_ATTACK_DESC = 'SORT_POKEMONS_BY_ATTACK_DESC';


export {
	GET_ALL_POKEMONS,
	GET_ALL_TYPES,
	GET_BY_ID,
	CLEAR_SORT,
	SEARCH_POKEMON,
	FILTER_POKEMONS_BY_TYPE,
	PAGINATION,
	PAGES,
	NEW_POKEMON,
	CHANGE_PAGE,
	SORT_POKEMONS_BY_ASC,
	SORT_POKEMONS_BY_DESC,
	SORT_POKEMONS_BY_ATTACK_ASC,
	SORT_POKEMONS_BY_ATTACK_DESC,
};


